### ISSUE TITLE
Revisar modelo de negocio y avancede desarrollo de ingresos e ingresos sin situación de fotos para sub sistema de presupuesto de kronos - crud y mid

### ISSUE THREAD

**Issue by JuanPiedrahita** [udistrital/api_financiera#245]
Revisar modelo de negocio de kronos y avance de los desarrollos en los ambientesde pruebas

**Comment by JuanPiedrahita** [comment]
Se realiza revisión del modelo de negocio de ingresos y modelo de base de datos teniendo en cuenta la [documentación ](https://drive.google.com/folderview?id=0B8NdjGOtWwjCMk1LMHpYQkRBeUk)entregada por Maria C. [Se genera documento de resumen](https://docs.google.com/document/d/1zFPgNkkfhipOJV9RBEyopsuZtfB9_IutPA11nnHqvTk/edit?usp=drivesdk).

**Comment by JuanPiedrahita** [comment]
Se realiza revisión de endpoints que se consumen desde el cliente para paso de api a microservicios, se genera [documento de análisis](https://docs.google.com/document/d/1YL2omZg_6JOKJrIq4I78IEFWcjPEZLjpRJAZW1g3FaA/edit?usp=drivesdk).

**Comment by miguelramirez93** [comment]
Se revisan los documentos , todo acorde a lo solicitado. Gracias.

**Comment by Miavega** [comment]
Se apoya la revisión de endpoints consumidos desde el cliente para paso de api a microservicios, indicándolos en el [documento de análisis](https://docs.google.com/document/d/1YL2omZg_6JOKJrIq4I78IEFWcjPEZLjpRJAZW1g3FaA/edit)

**Comment by miguelramirez93** [comment]
Revisado y aprobado
