### ISSUE TITLE
**api financiera** Ejecutar refactor para respuestas en json: api_financiera y api_mid_financiera . Agregar documentación de los endpoints modificados - Camilo

### ISSUE THREAD

**Issue by juancsr** [udistrital/api_financiera#250]
Por petición de los desarrolladores de Resoluciones, se quiere se haga un refactor en las API api_financiera y api_mid_financiera, para que se asegure funcionen los servicios: 

**mid**
* disponibilidad/ListaDisponibilidades/'

**crud**
* disponibilidad_apropiacion
* disponibilidad/SaldoCdp'
* compromiso
* unidad_ejecutora/1
* disponibilidad/TotalDisponibilidades/
* fuente_financiamiento_apropiacion
* apropiacion
* producto_rubro

Luego, deben desplegarse los cambios realizados en el servidor 254. 

- [x] Ejecutar resfactor en api_financiera
- [x] desplegar api_financiera
- [x] Ejecutar refactor en api_mid_financiera
- [x] despelgar api_mid_financiera

**Comment by juancsr** [comment]
### Commits y PullRequest del api_mid_financiera:
* https://github.com/udistrital/api_mid_financiera/pull/144
* https://github.com/udistrital/api_mid_financiera/pull/145

_Puesto que esos commits no de otro repositorio no se pueden asociar a este issue, adjunto los links de los pull request_

El **despliegue en jenkins para el api_financiera** se realizó en el proyecto https://intelligentia.udistrital.edu.co:8443/jenkins/job/financiera_api/
mediante el task #255

El **despleigue en jenkins para el api_mid_financiera** se realizó en el proyecto
https://intelligentia.udistrital.edu.co:8443/jenkins/job/financiera_mid_api/
mediante el task #163

**Comment by BOTOOM** [comment]
todo ok

**Comment by Soulfilip-UD** [comment]
Listo, revisado los cambios por el equipo de resoluciones. Tarea finalizada

Proceeding to close Issue :space_invader:
